version: "3.3"

services:
  ffserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "554:554"
      - "8090:8090"
    volumes:
      - ./ffserver.conf:/etc/ffserver.conf
      - ./data:/data
    restart: always